const target = document.getElementById('target')
let yes = document.getElementById('yes')
yes.addEventListener('click',()=> {alert("HOLA, DIANA ESPERO QUE NO TE MOLESTO POR ESTOS LINEAS. PRIMERO GRACIAS POR DARME LA OPORTUNIDAD DE CONOCERTE, LA VERDAD DESDE EL PRIMER DIA QUE TE VI, ME DIO MIEDO Y ESTABA BUSCANDO UNA SOLUCION DE COMO PUEDO TENER TU NUMERO, AL FINAL APERECIO TU AMIGA, SE QUE AHORA TENES MIEDO DE CONOCERNOS Y HABLAR DE NUESTRO VIDA, LO QUE ESPERO YO ES CONOCERTE MAS Y SALIRNOS UN DIA PARA HABLAR UN POCO DE NUESTRO VIDA,SE QUE NO VA SER FACIL DE LLEGAR SERNO ALGO EN LA VIDA PERO SI TU Y YO TENEMOS CONFIANZA ENTRE NOSOTROS, NUESTRO VIDA PUEDE CAMBIAR AUNQUE AHORA TENEMOS MIEDO DE HABLARNOS EN PERSONA. ESPERO QUE NO TE MOLESTO Y GRACIAS POR LLEGAR A MI VIDA SE QUE AHORA AUN NO SOMOS NADA PERO POCO A POCO LAS COSAS VA CAMBIAR SI ME PERMITES DAR UN OPORTUNIDAD DE CONOCERTE MAS Y LLEGAR HACER ALGUIEN EN TU VIDA. ESPERO NO PERDER COMUNICACION CON TIGO TAMBIEN Y ESO FUE TODO, GRACIAS POR LLEGAR A LEER HASTA AQUI. ESPERO LLEGAR A CONOCERTE MAS Y SALIRNOS UN DIA PARA CONOCERNOS BIEN, GRACIAS POR TODO.  ATT: ALEX MO COY");})
 function moveTarget(){
    const maxWidth = 800;
    const maxHeight = 800;

    const ranomX = Math.floor( Math.random()* maxWidth)
    const ranomY = Math.floor( Math.random()* maxHeight)
    target.style.left = ranomX + 'px';
    target.style.top = ranomY + 'px';

 }

target.addEventListener( 'mouseenter', function(){
    moveTarget();
})